export const bedsData = [
  // ---------------- ICU ----------------
  {
    id: "ICU-101",
    wardType: "ICU",
    wardName: "Critical Care Unit A",
    floor: 1,
    status: "Available",
    gender: "Any",
    patientName: null,
    severity: null,
    doctorAssigned: null,
    equipment: ["Ventilator", "Cardiac Monitor"],
  },
  {
    id: "ICU-102",
    wardType: "ICU",
    wardName: "Critical Care Unit A",
    floor: 1,
    status: "Occupied",
    gender: "Male",
    patientName: "Rahul Sharma",
    severity: "High",
    doctorAssigned: "Dr. Mehta",
    admissionTime: "2025-02-12T08:00:00",
    equipment: ["Ventilator", "Oxygen Support"],
  },
  {
    id: "ICU-103",
    wardType: "ICU",
    wardName: "Critical Care Unit A",
    floor: 1,
    status: "Cleaning",
    gender: "Any",
    patientName: null,
    severity: null,
    doctorAssigned: null,
    cleaningTime: 3,
    equipment: ["Cardiac Monitor"],
  },
  {
    id: "ICU-104",
    wardType: "ICU",
    wardName: "Critical Care Unit B",
    floor: 1,
    status: "Occupied",
    gender: "Female",
    patientName: "Anjali Verma",
    severity: "Medium",
    doctorAssigned: "Dr. Khan",
    admissionTime: "2025-02-12T10:30:00",
    equipment: ["Ventilator"],
  },

  // ---------------- GENERAL ----------------
  {
    id: "GEN-201",
    wardType: "General",
    wardName: "General Ward A",
    floor: 2,
    status: "Available",
    gender: "Any",
    patientName: null,
    severity: null,
    doctorAssigned: null,
  },
  {
    id: "GEN-202",
    wardType: "General",
    wardName: "General Ward A",
    floor: 2,
    status: "Occupied",
    gender: "Female",
    patientName: "Priya Singh",
    severity: "Low",
    doctorAssigned: "Dr. Roy",
    admissionTime: "2025-02-11T15:00:00",
  },
  {
    id: "GEN-203",
    wardType: "General",
    wardName: "General Ward B",
    floor: 2,
    status: "Available",
    gender: "Any",
    patientName: null,
    severity: null,
    doctorAssigned: null,
  },
  {
    id: "GEN-204",
    wardType: "General",
    wardName: "General Ward B",
    floor: 2,
    status: "Cleaning",
    gender: "Any",
    patientName: null,
    cleaningTime: 4,
  },
  {
    id: "GEN-205",
    wardType: "General",
    wardName: "General Ward B",
    floor: 2,
    status: "Occupied",
    gender: "Male",
    patientName: "Arjun Patel",
    severity: "Medium",
    doctorAssigned: "Dr. Sharma",
    admissionTime: "2025-02-12T09:15:00",
  },

  // ---------------- EMERGENCY ----------------
  {
    id: "EMG-301",
    wardType: "Emergency",
    wardName: "Emergency Bay 1",
    floor: 0,
    status: "Occupied",
    gender: "Male",
    patientName: "Karan Yadav",
    severity: "Critical",
    doctorAssigned: "Dr. Kapoor",
    admissionTime: "2025-02-12T12:00:00",
  },
  {
    id: "EMG-302",
    wardType: "Emergency",
    wardName: "Emergency Bay 1",
    floor: 0,
    status: "Available",
    gender: "Any",
    patientName: null,
  },
  {
    id: "EMG-303",
    wardType: "Emergency",
    wardName: "Emergency Bay 2",
    floor: 0,
    status: "Cleaning",
    gender: "Any",
    patientName: null,
    cleaningTime: 2,
  },
  {
    id: "EMG-304",
    wardType: "Emergency",
    wardName: "Emergency Bay 2",
    floor: 0,
    status: "Occupied",
    gender: "Female",
    patientName: "Neha Joshi",
    severity: "High",
    doctorAssigned: "Dr. Kapoor",
    admissionTime: "2025-02-12T11:45:00",
  },

  // ---------------- EXTRA GENERAL BEDS ----------------
  {
    id: "GEN-206",
    wardType: "General",
    wardName: "General Ward C",
    floor: 3,
    status: "Available",
    gender: "Any",
  },
  {
    id: "GEN-207",
    wardType: "General",
    wardName: "General Ward C",
    floor: 3,
    status: "Occupied",
    gender: "Female",
    patientName: "Simran Kaur",
    severity: "Low",
    doctorAssigned: "Dr. Roy",
    admissionTime: "2025-02-12T07:00:00",
  },
  {
    id: "GEN-208",
    wardType: "General",
    wardName: "General Ward C",
    floor: 3,
    status: "Available",
    gender: "Any",
  },
];
